// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "AutoCompletionService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::AutoCompletion;

class AutoCompletionServiceHandler : virtual public AutoCompletionServiceIf {
 public:
  AutoCompletionServiceHandler() {
    // Your initialization goes here
  }

  void query(std::string& _return, const std::string& prefix) {
    // Your implementation goes here
    _return = std::string("echo from server ") + prefix;
    printf("query\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<AutoCompletionServiceHandler> handler(new AutoCompletionServiceHandler());
  shared_ptr<TProcessor> processor(new AutoCompletionServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

