//
// Autogenerated by Thrift Compiler (1.0.0-dev)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./autoCompletion_types');
//HELPER FUNCTIONS AND STRUCTURES

AutoCompletionService_query_args = function(args) {
  this.prefix = null;
  if (args) {
    if (args.prefix !== undefined) {
      this.prefix = args.prefix;
    }
  }
};
AutoCompletionService_query_args.prototype = {};
AutoCompletionService_query_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRING) {
        this.prefix = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AutoCompletionService_query_args.prototype.write = function(output) {
  output.writeStructBegin('AutoCompletionService_query_args');
  if (this.prefix !== null && this.prefix !== undefined) {
    output.writeFieldBegin('prefix', Thrift.Type.STRING, 1);
    output.writeString(this.prefix);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AutoCompletionService_query_result = function(args) {
  this.success = null;
  this.qe = null;
  if (args instanceof ttypes.QueryException) {
    this.qe = args;
    return;
  }
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.qe !== undefined) {
      this.qe = args.qe;
    }
  }
};
AutoCompletionService_query_result.prototype = {};
AutoCompletionService_query_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.qe = new ttypes.QueryException();
        this.qe.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

AutoCompletionService_query_result.prototype.write = function(output) {
  output.writeStructBegin('AutoCompletionService_query_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  if (this.qe !== null && this.qe !== undefined) {
    output.writeFieldBegin('qe', Thrift.Type.STRUCT, 1);
    this.qe.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

AutoCompletionServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
AutoCompletionServiceClient.prototype = {};
AutoCompletionServiceClient.prototype.seqid = function() { return this._seqid; }
AutoCompletionServiceClient.prototype.new_seqid = function() { return this._seqid += 1; }
AutoCompletionServiceClient.prototype.query = function(prefix, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_query(prefix);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_query(prefix);
  }
};

AutoCompletionServiceClient.prototype.send_query = function(prefix) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('query', Thrift.MessageType.CALL, this.seqid());
  var args = new AutoCompletionService_query_args();
  args.prefix = prefix;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

AutoCompletionServiceClient.prototype.recv_query = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new AutoCompletionService_query_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.qe) {
    return callback(result.qe);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('query failed: unknown result');
};
AutoCompletionServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
AutoCompletionServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

AutoCompletionServiceProcessor.prototype.process_query = function(seqid, input, output) {
  var args = new AutoCompletionService_query_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.query.length === 1) {
    Q.fcall(this._handler.query, args.prefix)
      .then(function(result) {
        var result = new AutoCompletionService_query_result({success: result});
        output.writeMessageBegin("query", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result = new AutoCompletionService_query_result(err);
        output.writeMessageBegin("query", Thrift.MessageType.REPLY, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.query(args.prefix,  function (err, result) {
      var result = new AutoCompletionService_query_result((err != null ? err : {success: result}));
      output.writeMessageBegin("query", Thrift.MessageType.REPLY, seqid);
      result.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
}

